[build]
  command = "npm run build" # Or your build command
  publish = "dist"          # Vite's default output dir

# This rule handles SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200