import React from "react";
import { Link } from "react-router-dom";
import { motion as Motion } from "framer-motion";
import { ArrowRightIcon, BoltIcon, ShieldCheckIcon, SparklesIcon } from "@heroicons/react/24/outline";

const Home = () => <main className="app-shell relative flex min-h-screen items-center justify-center overflow-hidden px-5 py-12 text-center sm:px-8">
  <div className="pointer-events-none absolute left-[-10rem] top-[-10rem] h-[28rem] w-[28rem] rounded-full bg-indigo-300/20 blur-3xl" /><div className="pointer-events-none absolute bottom-[-12rem] right-[-8rem] h-[30rem] w-[30rem] rounded-full bg-emerald-300/15 blur-3xl" />
  <Motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="relative z-10 flex max-w-3xl flex-col items-center">
    <span className="mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white/75 px-4 py-2 text-xs font-bold uppercase tracking-[0.16em] text-indigo-600 shadow-sm"><SparklesIcon className="h-4 w-4" /> Conversations, reimagined</span>
    <h1 className="text-5xl font-black tracking-[-0.06em] text-slate-900 sm:text-7xl">A better place for <span className="bg-gradient-to-r from-indigo-600 via-violet-600 to-emerald-500 bg-clip-text text-transparent">real conversations.</span></h1>
    <p className="mt-6 max-w-xl text-base leading-7 text-slate-500 sm:text-lg">ChatApp keeps your conversations fast, focused, and delightfully human—with real-time messaging and an AI companion when you need one.</p>
    <div className="mt-9 flex w-full flex-col justify-center gap-3 sm:w-auto sm:flex-row"><Link to="/login" className="group inline-flex items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-7 py-3.5 text-sm font-bold text-white shadow-xl shadow-indigo-300/30 transition hover:-translate-y-1 hover:bg-indigo-700">Open your inbox <ArrowRightIcon className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link><Link to="/register" className="inline-flex items-center justify-center rounded-2xl border border-slate-200 bg-white/80 px-7 py-3.5 text-sm font-bold text-slate-700 shadow-sm transition hover:-translate-y-1 hover:border-indigo-200 hover:text-indigo-700">Create an account</Link></div>
    <div className="mt-14 grid w-full max-w-xl grid-cols-3 gap-3 text-left"><div className="rounded-2xl border border-white/80 bg-white/60 p-4 shadow-sm"><BoltIcon className="h-5 w-5 text-amber-500" /><p className="mt-3 text-xs font-bold text-slate-700">Real-time</p><p className="mt-1 text-[11px] text-slate-400">Instant delivery</p></div><div className="rounded-2xl border border-white/80 bg-white/60 p-4 shadow-sm"><ShieldCheckIcon className="h-5 w-5 text-emerald-500" /><p className="mt-3 text-xs font-bold text-slate-700">Private</p><p className="mt-1 text-[11px] text-slate-400">Session-secured</p></div><div className="rounded-2xl border border-white/80 bg-white/60 p-4 shadow-sm"><SparklesIcon className="h-5 w-5 text-indigo-500" /><p className="mt-3 text-xs font-bold text-slate-700">Smarter</p><p className="mt-1 text-[11px] text-slate-400">AI-ready chats</p></div></div>
  </Motion.div>
</main>;
export default Home;